### ISSUE TITLE
Unable to load the requested file: Frontend/daftar_view.php

### ISSUE THREAD

**Issue by alanyukeroo** [yufieko/ekiosk-perpus#1]
I dont know if the problem is the daftar_view.php in Frontend folder doesnt exist, if it so, could you please provide / update the Frontend/daftar_view.php files ? Thankyou sir. 
![selection_028](https://user-images.githubusercontent.com/12026322/37355157-dd9f63c6-2715-11e8-907f-120dc2dfec24.png)

**Comment by yufieko** [comment]
actually there was no page for register back there, so I can't help you with this issue. You can try to make it by your self. If anything you want me to help about existing code or structure, you can ask me here. Good luck.
